language: node_js
node_js:
  - "6.1"
  - "5.11"
  - "4.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
    - npm test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libc6 libgif-dev libpng-dev libjpeg8-dev libpango1.0-dev libcairo2-dev
dist: trusty
